version: 2.1

orbs:
  node: circleci/node@5.1.0
  docker: circleci/docker@2.4.0
  snyk: snyk/snyk@2.0.1

jobs:
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages
      - run: |
          echo "Installed dependencies"
  build-and-push:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: amidewing/education-space
      - docker/push:
          image: amidewing/education-space
  scan:
    docker:
      - image: cimg/node:16.10
    environment:
      IMAGE_NAME: amidewing/education-space
    steps:
      - checkout
      - setup_remote_docker
      - docker/check
      - docker/build:
          image: $IMAGE_NAME
      - snyk/scan:
          docker-image-name: $IMAGE_NAME

workflows:
  simple_workflow:
    jobs:
      - build
      - node/test:
          name: test
          requires:
            - build
      - build-and-push:
          requires:
            - test
      - scan:
          requires:
            - build