version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages
      - run: |
          echo "Installed dependencies"
  build-and-push:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: amidewing/education-space
      - docker/push:
          image: amidewing/education-space

workflows:
  simple_workflow:
    jobs:
      - build
      - node/test:
          name: test
          requires:
            - build
      - build-and-push:
          requires:
            - test