version: 2.1

orbs:
  node: circleci/node@5.0.1

jobs:
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages
      - run: |
          echo "Installed dependencies"


workflows:
  simple_workflow:
    jobs:
      - build
      - node/test:
          requires:
            - build